---

- name: rhel system role
  roles:
    - rhel-system-roles.selinux
  hosts: webservers
  vars:
    selinux_booleans:
      - { name: 'httpd_can_network_connect', state: 'on', persistent: 'yes' }
  become: yes
