---

- name: Create Users for Webservers
  hosts: webservers
  become: yes
  gather_facts: no
  pre_tasks:
    - name: Include  Users List
      include_vars: user_list.yml

    - name: Include secret
      include_vars: secret.yml

  tasks:
    - name: Webserver Users
      user:
        name: "{{ item['username'] }}"
        uid: "{{ item['uid'] }}"
        password: "{{ user_password }}"
        groups: ['wheel']
        shell: /bin/bash
      loop: "{{ users }}"
      when: (item['uid']|string)[0] == "1"

    - name: Push keys
      authorized_key:
        user: "{{ item['username'] }}"
        state: present
        key: "{{ lookup('file', '/home/automation/.ssh/id_rsa.pub') }}"
      loop: "{{ users }}"
      when: (item['uid']|string)[0] == "1"


- name: Create Users for DB
  hosts: database
  become: yes
  gather_facts: no
  pre_tasks:
    - name: Include  Users List
      include_vars: user_list.yml

    - name: Include secret
      include_vars: secret.yml

  tasks:
    - name: DB Users
      user:
        name: "{{ item['username'] }}"
        uid: "{{ item['uid'] }}"
        password: "{{ user_password }}"
        groups: ['wheel']
        shell: /bin/bash
      loop: "{{ users }}"
      when: (item['uid']|string)[0] == "2"

    - name: Push keys
      authorized_key:
        user: "{{ item['username'] }}"
        state: present
        key: "{{ lookup('file', '/home/automation/.ssh/id_rsa.pub') }}"
      loop: "{{ users }}"
      when: (item['uid']|string)[0] == "2"
