---

- name: Create/Remove Users
  hosts: nodes
  gather_facts: no
  vars:
    - ansible_user: ansible
  pre_tasks:
    - name: Include vault
      include_vars: 
        file: secret.yml
        name: secret
      tags: always
  tasks:
    - name: Create User
      user:
        name: "{{ secret[inventory_hostname]['user'] }}" 
        password: "{{ secret[inventory_hostname]['password'] }}" 
        group: wheel
      become: yes
      tags: create

    - name: Remove User
      user:
        name: "{{ secret[inventory_hostname]['user'] }}" 
        state: absent
        remove: yes
      become: yes
      tags: destroy

  
- name: Push/Pull Key
  hosts: webserver
  gather_facts: no
  vars:
    - ansible_user: ansible
  pre_tasks:
    - name: Include vault
      include_vars: 
        file: secret.yml
        name: secret
      tags: always
  tasks:
    - name: push ssh key
      authorized_key:
        user: "{{ secret[inventory_hostname]['user'] }}"
        state: present
        key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"
      become: yes
      tags: create

    - name: Check if dir removed
      stat:
        path: "/home/{{ secret[inventory_hostname]['user'] }}"
      register: st
      tags: destroy

    - name: pull ssh key
      authorized_key:
        user: "{{ secret[inventory_hostname]['user'] }}"
        state: absent
      become: yes
      when: st.stat.exists
      tags: destroy


- name: pw Sudo
  hosts: combined
  gather_facts: no
  vars:
    - ansible_user: ansible
  tasks:
    - name: Replace line in sudoers
      lineinfile:
        path: /etc/sudoers
        regexp: '%wheel  ALL=(ALL)       ALL'
        line: "%wheel  ALL=(ALL)       NOPASSWD: ALL"
      become: yes
      tags: create

    - name: Replace line in sudoers
      lineinfile:
        path: /etc/sudoers
        regexp: "%wheel  ALL=(ALL)       NOPASSWD: ALL"
        line: '%wheel  ALL=(ALL)       ALL'
      become: yes
      tags: destroy
