---

- name: Test vault
  hosts: nodes
  gather_facts: no
  tasks:
  - name: Include Vault file
    include_vars:
      file: secret.yml
      name: secret

  - name: Debug print
    debug:
      msg: "{{ secret[inventory_hostname]['user'] }}"

  - name: Debug Names
    debug:
      msg: "{{ inventory_hostname }}"
