---
# tasks file for roles/sample-mysql
  - name: Partition
    parted:
      number: 1
      device: /dev/sdb
      part_end: 800MB
      state: present

  - name: Create VG
    lvg:
      vg: vg_database
      pvs: /dev/sdb1

  - name: Create lvm
    lvol:
      vg: vg_database
      lv: lv_mysql
      size: 512m

  - name: lvm Filesystem
    filesystem:
      dev: /dev/mapper/vg_database-lv_mysql
      fstype: xfs

  - name: Mount it
    mount:
      path: /mnt/mysql_backups
      src: /dev/mapper/vg_database-lv_mysql 
      fstype: xfs
      state: mounted
